language: node_js
node_js:
   - “7”
 
branches:
   only:
      - master

before_script:
   - npm install -g firebase-tools

script:
   - cd functions
   - npm install
   - cd ..

after_success:
   - firebase deploy --token $FIREBASE_TOKEN